In [1]:
import numpy as np

In [2]:
#ejercicio 1
"""
Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).
"""
A=np.arange(1, 8*8+1).reshape(8,8)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [3]:
#ejercicio 2
"""
i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.
"""
C=np.arange(1, 8*8+1)
for i, el in enumerate(C):
    if '3' in str(el):
        C[i]=-99
C=C.reshape(8,8).transpose()

In [6]:
#ejercicio 3
"""i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]
[0.45 0.46 0.47 0.48 0.49]
[0.5 0.51 0.52 0.53 0.54]
[0.55 0.56 0.57 0.58 0.59]
[0.6 0.61 0.62 0.63 0.64]
[0.65 0.66 0.67 0.68 0.69]
[0.7 0.71 0.72 0.73 0.74]
[0.75 0.76 0.77 0.78 0.79]]"""

B=np.arange(0.4, 0.8, 0.01).reshape(8, 5)
"""
ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas
"""
#matriz de union de B y C
D=np.append(B, C, axis=1)
"""iii. Agregar una linea al final con el promedio de cada columna"""
E=np.append(D, np.average(D, axis=0).reshape((1,13)), axis=0)
"""iv. Agregar una columna al final con el valor maximo de cada fila"""
F=np.append(E, np.max(E, axis=1).reshape((9,1)), axis=1)
file=open('ejercicio3.txt', 'w')
file.write(f'{F}')
file.close()